### ISSUE TITLE
Error: write EPROTO 101057795 while running npm install handbrake-js 

### ISSUE THREAD

**Issue by HanrichPotgieter** [75lb/handbrake-js#28]
Platform: Windows 64bit
Node: 9.11.1
npm: 5.6.0

The following error occurs when attempting to install handbrake via npm

![image](https://user-images.githubusercontent.com/8564706/39178420-fa6ffbac-47b1-11e8-96d1-5e0390d0cfab.png)

It seems to originate from the install script while attempting to download and extract the executable file.

**Comment by HanrichPotgieter** [comment]
After some investigation, I found that the following error occurs when using a newer version of node.js. This error does not occur when using node 8.3.0

**Comment by 75lb** [comment]
Hi, sorry for the delay. Thanks for pointing out this issue - I'll look into it later today.

**Comment by 75lb** [comment]
fixed and released in v3.0.3

**Comment by pmoleri** [comment]
I'm still experiencing this in node v8.11.1, I just created a pull request that solved the issue for me.

**Comment by jensHartfelt** [comment]
It works for me now with handbrake 3.0.4 and node 8.3.0, 8.9.4 and 9.11.2 on windows 10

**Comment by pmoleri** [comment]
That's it 3.0.4 includes the new fix.
I just noted that 3.0.4 fails to install in node 8.1.4 and I guess any other previous node version.
One option would be to rewrite the fix to only affect node versions >= 8.6.0 and < 10.
The other option is that users that want to use it in node < 8.6.0 keep using handbrake-js 3.0.3.

**Comment by 75lb** [comment]
hi, thanks for letting me know - fixed in v3.0.5.
